### ISSUE TITLE
Log error 'missing content for CA bundle'

### ISSUE THREAD

**Issue by cmacrae** [neoskop/cert-manager-webhook-dnsimple#4]
Hey people 👋 Thank you so much for this project!  
I had been trying to implement this myself a while back but gave up - so I was delighted to come across this when I decided to check recently if anyone had tackled it ❤️ 

After deploying via the chart, I'm seeing this message being constantly spat out in the logs:
```
E0824 22:41:28.654568       1 configmap_cafile_content.go:246] key failed with : missing content for CA bundle "client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
```
Any ideas?

**Comment by arnediekmann** [comment]
Hi @cmacrae, I waited a lot for this plug-in as well until it got to a point where we needed it so desperately in a project that I was willing to just give it a shot. The code needed was actually not complicated at all - sometimes you just need the proper motivation to write it :wink:

The log line you attached is one I usually see in the plugin's log first until the client ca is seemingly injected after a few moments. Then everything works fine. Can you check that the `cert-manager-webhook-dnsimple:webhook-authentication-reader` role binding exists in the `kube-system` namespace, e.g.:

```
$ k get rolebinding cert-manager-webhook-dnsimple:webhook-authentication-reader -n kube-system
```

and if it does: can you elaborate on the environment (say GKE, AKS et al.) and the Kubernetes and cert-manager versions?

**Comment by cmacrae** [comment]
Thanks for the prompt reply @arnediekmann 👋   

Yep, the role binding does exist :) Here's some info on my environment:  
- On prem (at home... 🏠 ) deployment on the metal  
- ArgoCD with a bunch of Helm charts for deployment
- cert-manager `0.15.2` chart deployed (all looks well)
- cert-manager-webhook-dnsimple `0.0.3` chart deployed

**cert-manager chart values**
Just turning on CRD deployment (values are nested as I'm using `requirements.yaml`)
```yaml
cert-manager:
  installCRDs: true
```

**cert-manager-webhook-dnsimple chart values**
(Same again with the nested values)
```yaml
cert-manager-webhook-dnsimple:
  image:
    repository: neoskop/cert-manager-webhook-dnsimple
    tag: 0.0.3
  dnsimple:
    account: < REDACTED >
    token: < REDACTED >
  clusterIssuer:
    staging:
      enabled: true
    email: < REDACTED >
```

Let me know if there's anything else I can provide to help debug :)
